### ISSUE TITLE
Prepopulate reasonable default value

### ISSUE THREAD

**Issue by probonopd** [ximion/metainfocreator#2]
Hi @ximion thanks for making this useful web app.

Maybe you'd like to prepopulate reasonable default values, like I had done in http://output.jsbin.com/qoqukof - seeing reasonable default values always helps me to know what I am supposed to enter without thinking much.

**Comment by ximion** [comment]
I'm a bit wary of that, as that would create a valid form with the user not filling out all data.
For some values, like the metadata license, we could pick a default though.
At the moment, I am going with help texts as the `placeholder` property of input elements (but Bulma renders those quite faintly, so maybe I'll simply increase their visibility a bit).

**Comment by ximion** [comment]
All fields have a default value or helptext as placeholder now, and some even generate default values based on user input.
