### ISSUE TITLE
Ambiguosly choosing LGPL license

### ISSUE THREAD

**Issue by PanderMusubi** [ximion/metainfocreator#5]
When choosing a license, it is ambiguous what is exactly chosen. See the screenshot

![license](https://user-images.githubusercontent.com/198964/81943645-ef291b80-95fb-11ea-8541-8a3b24362601.png)

And the licenses in https://github.com/ximion/metainfocreator/blob/master/src/assets/spdx-licenses.json#L1019

For the user it is not clear why there are duplicates or what is the impacht of chosing one of two licenses with the same name.

**Comment by ximion** [comment]
Indeed! This is resolved now by permitting only new-style SPDX license IDs to be chosen.
