### ISSUE TITLE
Is my TLD unsupported for rDNS?

### ISSUE THREAD

**Issue by therealchfkch** [ximion/metainfocreator#58]
As you can see in the image below, the form does not accept my domain or the according rDNS setting.
I suspect it is either because of the .dev top level domain or the missing subdomain.
What am i missing here or is this a bug?

![image](https://github.com/user-attachments/assets/e6c1e4ca-8d01-49f8-9a28-822a3ca49c4c)

**Comment by ximion** [comment]
Your TLD is supported, but you are missing the third component of your ID (the software name). A component ID always has at least three parts.

**Comment by therealchfkch** [comment]
Okay, i was irritated because i got an auto-suggestion when typing the URL. Thanks for clarifying.
