### ISSUE TITLE
Missing secondary category spell checker

### ISSUE THREAD

**Issue by PanderMusubi** [ximion/metainfocreator#6]
Missing secondary category spell checker

https://github.com/ximion/metainfocreator/blob/master/src/assets/categories-secondary.json#L240

**Comment by ximion** [comment]
What do you mean? There is no valid category for "SpellChecker": https://specifications.freedesktop.org/menu-spec/latest/apas02.html

**Comment by PanderMusubi** [comment]
Thanks for the link to upstream. Have reported it there https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/57

**Comment by ximion** [comment]
Jup, that's the way to go :-)
Thank you for forwarding the issue!
